### ISSUE TITLE
Bridge raising access denied exception when missing `content-type` in the request

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-bridge#598]
When an operation against the bridge is executed without specifying the `content-type` in the header, the following error is logged in the pod and an "Internal Server Error" string is returned to the HTTP client.

```shell
2022-02-16 13:38:54 ERROR RoutingContext: - Unhandled exception in router
io.vertx.core.file.FileSystemException: Unable to create folder at path 'file-uploads'
	at io.vertx.core.file.impl.FileSystemImpl$12.perform(FileSystemImpl.java:950) ~[vertx-core-4.2.4.jar:4.2.4]
	at io.vertx.core.file.impl.FileSystemImpl$12.perform(FileSystemImpl.java:932) ~[vertx-core-4.2.4.jar:4.2.4]
	at io.vertx.core.file.impl.FileSystemImpl.mkdirsBlocking(FileSystemImpl.java:345) ~[vertx-core-4.2.4.jar:4.2.4]
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.makeUploadDir(BodyHandlerImpl.java:248) ~[vertx-web-4.2.4.jar:4.2.4]
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.<init>(BodyHandlerImpl.java:186) ~[vertx-web-4.2.4.jar:4.2.4]
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl.handle(BodyHandlerImpl.java:84) ~[vertx-web-4.2.4.jar:4.2.4]
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl.handle(BodyHandlerImpl.java:44) ~[vertx-web-4.2.4.jar:4.2.4]
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212) ~[vertx-web-4.2.4.jar:4.2.4]
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163) [vertx-web-4.2.4.jar:4.2.4]
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141) [vertx-web-4.2.4.jar:4.2.4]
	at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:67) [vertx-web-4.2.4.jar:4.2.4]
	at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:37) [vertx-web-4.2.4.jar:4.2.4]
	at io.vertx.core.http.impl.Http1xServerRequestHandler.handle(Http1xServerRequestHandler.java:67) [vertx-core-4.2.4.jar:4.2.4]
	at io.vertx.core.http.impl.Http1xServerRequestHandler.handle(Http1xServerRequestHandler.java:30) [vertx-core-4.2.4.jar:4.2.4]
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:50) [vertx-core-4.2.4.jar:4.2.4]
	at io.vertx.core.impl.DuplicatedContext.emit(DuplicatedContext.java:168) [vertx-core-4.2.4.jar:4.2.4]
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:145) [vertx-core-4.2.4.jar:4.2.4]
	at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:156) [vertx-core-4.2.4.jar:4.2.4]
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:153) [vertx-core-4.2.4.jar:4.2.4]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:99) [netty-codec-http-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.vertx.core.http.impl.Http1xUpgradeToH2CHandler.channelRead(Http1xUpgradeToH2CHandler.java:116) [vertx-core-4.2.4.jar:4.2.4]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314) [netty-codec-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435) [netty-codec-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) [netty-codec-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.vertx.core.http.impl.Http1xOrH2CHandler.end(Http1xOrH2CHandler.java:61) [vertx-core-4.2.4.jar:4.2.4]
	at io.vertx.core.http.impl.Http1xOrH2CHandler.channelRead(Http1xOrH2CHandler.java:38) [vertx-core-4.2.4.jar:4.2.4]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-common-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.73.Final.jar:4.1.73.Final]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.nio.file.AccessDeniedException: /opt/strimzi/file-uploads
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389) ~[?:?]
	at java.nio.file.Files.createDirectory(Files.java:690) ~[?:?]
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:797) ~[?:?]
	at java.nio.file.Files.createDirectories(Files.java:783) ~[?:?]
	at io.vertx.core.file.impl.FileSystemImpl$12.perform(FileSystemImpl.java:940) ~[vertx-core-4.2.4.jar:4.2.4]
	... 55 more
```

The above error was raised by issuing the following example request via `cURL` where the `content-type` is missing.

```shell
curl -X POST \
  http://localhost:8080/topics/my-topic \
  -d '{
    "records": [
        {
            "key": "key-1",
            "value": "value-1"
        },
        {
            "key": "key-2",
            "value": "value-2"
        }
    ]
}'
```

By adding the line `-H 'content-type: application/vnd.kafka.json.v2+json'` the operation works fine.

My feeling is that the Vert.x router is defaulting to some "built-in" route which tries to create a `file-uploads` folder in a read-only `/opt/strimzi/` path on the pod, when it's not able to route the request properly due to the missing `content-type` because how it's defined in the OpenAPI specification.

**Comment by scholzj** [comment]
I guess we can try to capture these and return some nicer error :-D

**Comment by scholzj** [comment]
We should come up with some _wanna be funny_ error message like Google has ;-)

**Comment by joschi** [comment]
@ppatierno @scholzj This is still happening in Strimzi Kafka Bridge 0.32.0.

Do you want me to open a new issue or do you want to reopen this issue?

```text
❯ curl localhost:8080
{"bridge_version":"0.32.0"}

❯ curl -iSf -X POST -d '{"records":[{"key":"key-1", "value": "value-1"},{"key":"key-2", "value":"value-2"}]}' localhost:8080/topics/bridge-test
HTTP/1.1 500 Internal Server Error
content-length: 21

curl: (22) The requested URL returned error: 500

❯ curl -iSf -H 'content-type: application/vnd.kafka.json.v2+json' -X POST -d '{"records":[{"key":"key-1", "value": "value-1"},{"key":"key-2", "value":"value-2"}]}' localhost:8080/topics/bridge-test
HTTP/1.1 200 OK
content-type: application/vnd.kafka.v2+json
content-length: 67

{"offsets":[{"partition":0,"offset":0},{"partition":0,"offset":1}]}
```

Logs:
```text
2025-11-07 07:48:48 ERROR [vert.x-eventloop-thread-0] RoutingContext: - Unhandled exception in router
io.vertx.core.file.FileSystemException: Unable to create folder at path 'file-uploads'
	at io.vertx.core.file.impl.FileSystemImpl$12.perform(FileSystemImpl.java:950) ~[io.vertx.vertx-core-4.5.14.jar:4.5.14]
	at io.vertx.core.file.impl.FileSystemImpl$12.perform(FileSystemImpl.java:932) ~[io.vertx.vertx-core-4.5.14.jar:4.5.14]
	at io.vertx.core.file.impl.FileSystemImpl.mkdirsBlocking(FileSystemImpl.java:345) ~[io.vertx.vertx-core-4.5.14.jar:4.5.14]
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.makeUploadDir(BodyHandlerImpl.java:297) ~[io.vertx.vertx-web-4.5.14.jar:4.5.14]
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.<init>(BodyHandlerImpl.java:232) ~[io.vertx.vertx-web-4.5.14.jar:4.5.14]
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl.handle(BodyHandlerImpl.java:126) ~[io.vertx.vertx-web-4.5.14.jar:4.5.14]
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl.handle(BodyHandlerImpl.java:45) ~[io.vertx.vertx-web-4.5.14.jar:4.5.14]
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1283) ~[io.vertx.vertx-web-4.5.14.jar:4.5.14]
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177) ~[io.vertx.vertx-web-4.5.14.jar:4.5.14]
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:151) ~[io.vertx.vertx-web-4.5.14.jar:4.5.14]
	at io.vertx.ext.web.impl.RoutingContextImpl.route(RoutingContextImpl.java:100) ~[io.vertx.vertx-web-4.5.14.jar:4.5.14]
	at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:69) ~[io.vertx.vertx-web-4.5.14.jar:4.5.14]
	at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:37) ~[io.vertx.vertx-web-4.5.14.jar:4.5.14]
	at io.vertx.core.http.impl.Http1xServerRequestHandler.handle(Http1xServerRequestHandler.java:150) ~[io.vertx.vertx-core-4.5.14.jar:4.5.14]
	at io.vertx.core.http.impl.Http1xServerRequestHandler.handle(Http1xServerRequestHandler.java:42) ~[io.vertx.vertx-core-4.5.14.jar:4.5.14]
	at io.vertx.core.impl.ContextImpl.emit(ContextImpl.java:342) ~[io.vertx.vertx-core-4.5.14.jar:4.5.14]
	at io.vertx.core.impl.DuplicatedContext.emit(DuplicatedContext.java:163) ~[io.vertx.vertx-core-4.5.14.jar:4.5.14]
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:174) ~[io.vertx.vertx-core-4.5.14.jar:4.5.14]
	at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:159) ~[io.vertx.vertx-core-4.5.14.jar:4.5.14]
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:153) ~[io.vertx.vertx-core-4.5.14.jar:4.5.14]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[io.netty.netty-transport-4.1.118.Final.jar:4.1.118.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[io.netty.netty-transport-4.1.118.Final.jar:4.1.118.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[io.netty.netty-transport-4.1.118.Final.jar:4.1.118.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93) ~[io.netty.netty-transport-4.1.118.Final.jar:4.1.118.Final]
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.onHttpRequestChannelRead(WebSocketServerExtensionHandler.java:158) ~[io.netty.netty-codec-http-4.1.118.Final.jar:4.1.118.Final]
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:82) ~[io.netty.netty-codec-http-4.1.118.Final.jar:4.1.118.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[io.netty.netty-transport-4.1.118.Final.jar:4.1.118.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[io.netty.netty-transport-4.1.118.Final.jar:4.1.118.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[io.netty.netty-transport-4.1.118.Final.jar:4.1.118.Final]
	at io.vertx.core.http.impl.Http1xUpgradeToH2CHandler.channelRead(Http1xUpgradeToH2CHandler.java:124) ~[io.vertx.vertx-core-4.5.14.jar:4.5.14]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[io.netty.netty-transport-4.1.118.Final.jar:4.1.118.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[io.netty.netty-transport-4.1.118.Final.jar:4.1.118.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[io.netty.netty-transport-4.1.118.Final.jar:4.1.118.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[io.netty.netty-codec-4.1.118.Final.jar:4.1.118.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[io.netty.netty-codec-4.1.118.Final.jar:4.1.118.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:455) ~[io.netty.netty-codec-4.1.118.Final.jar:4.1.118.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[io.netty.netty-codec-4.1.118.Final.jar:4.1.118.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[io.netty.netty-transport-4.1.118.Final.jar:4.1.118.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[io.netty.netty-transport-4.1.118.Final.jar:4.1.118.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[io.netty.netty-transport-4.1.118.Final.jar:4.1.118.Final]
	at io.vertx.core.http.impl.Http1xOrH2CHandler.end(Http1xOrH2CHandler.java:61) ~[io.vertx.vertx-core-4.5.14.jar:4.5.14]
	at io.vertx.core.http.impl.Http1xOrH2CHandler.channelRead(Http1xOrH2CHandler.java:38) ~[io.vertx.vertx-core-4.5.14.jar:4.5.14]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[io.netty.netty-transport-4.1.118.Final.jar:4.1.118.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[io.netty.netty-transport-4.1.118.Final.jar:4.1.118.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[io.netty.netty-transport-4.1.118.Final.jar:4.1.118.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1357) ~[io.netty.netty-transport-4.1.118.Final.jar:4.1.118.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[io.netty.netty-transport-4.1.118.Final.jar:4.1.118.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[io.netty.netty-transport-4.1.118.Final.jar:4.1.118.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:868) ~[io.netty.netty-transport-4.1.118.Final.jar:4.1.118.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[io.netty.netty-transport-4.1.118.Final.jar:4.1.118.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:796) ~[io.netty.netty-transport-4.1.118.Final.jar:4.1.118.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:732) ~[io.netty.netty-transport-4.1.118.Final.jar:4.1.118.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:658) ~[io.netty.netty-transport-4.1.118.Final.jar:4.1.118.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[io.netty.netty-transport-4.1.118.Final.jar:4.1.118.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:998) ~[io.netty.netty-common-4.1.118.Final.jar:4.1.118.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[io.netty.netty-common-4.1.118.Final.jar:4.1.118.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty.netty-common-4.1.118.Final.jar:4.1.118.Final]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.nio.file.AccessDeniedException: /opt/strimzi/file-uploads
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:397) ~[?:?]
	at java.nio.file.Files.createDirectory(Files.java:700) ~[?:?]
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:807) ~[?:?]
	at java.nio.file.Files.createDirectories(Files.java:793) ~[?:?]
	at io.vertx.core.file.impl.FileSystemImpl$12.perform(FileSystemImpl.java:940) ~[io.vertx.vertx-core-4.5.14.jar:4.5.14]
	... 57 more
2025-11-07 07:49:05 INFO  [vert.x-eventloop-thread-0] send:49 - [2095516019] SEND Request: from 127.0.0.1:46908, method = POST, path = /topics/bridge-test
2025-11-07 07:49:05 INFO  [vert.x-eventloop-thread-0] AbstractConfig:371 - ProducerConfig values:
	acks = -1
	batch.size = 16384
	bootstrap.servers = [my-cluster-kafka-bootstrap.kafka-cluster.svc.cluster.local:9092]
	buffer.memory = 33554432
	client.dns.lookup = use_all_dns_ips
	client.id = producer-1
	compression.gzip.level = -1
	compression.lz4.level = 9
	compression.type = none
	compression.zstd.level = 3
	connections.max.idle.ms = 540000
	delivery.timeout.ms = 120000
	enable.idempotence = true
	enable.metrics.push = true
	interceptor.classes = [io.opentelemetry.instrumentation.kafkaclients.v2_6.TracingProducerInterceptor]
	key.serializer = class org.apache.kafka.common.serialization.ByteArraySerializer
	linger.ms = 5
	max.block.ms = 60000
	max.in.flight.requests.per.connection = 5
	max.request.size = 1048576
	metadata.max.age.ms = 300000
	metadata.max.idle.ms = 300000
	metadata.recovery.rebootstrap.trigger.ms = 300000
	metadata.recovery.strategy = rebootstrap
	metric.reporters = [org.apache.kafka.common.metrics.JmxReporter]
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	partitioner.adaptive.partitioning.enable = true
	partitioner.availability.timeout.ms = 0
	partitioner.class = null
	partitioner.ignore.keys = false
	receive.buffer.bytes = 32768
	reconnect.backoff.max.ms = 1000
	reconnect.backoff.ms = 50
	request.timeout.ms = 30000
	retries = 2147483647
	retry.backoff.max.ms = 1000
	retry.backoff.ms = 100
	sasl.client.callback.handler.class = null
	sasl.jaas.config = [hidden]
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.login.callback.handler.class = null
	sasl.login.class = null
	sasl.login.connect.timeout.ms = null
	sasl.login.read.timeout.ms = null
	sasl.login.refresh.buffer.seconds = 300
	sasl.login.refresh.min.period.seconds = 60
	sasl.login.refresh.window.factor = 0.8
	sasl.login.refresh.window.jitter = 0.05
	sasl.login.retry.backoff.max.ms = 10000
	sasl.login.retry.backoff.ms = 100
	sasl.mechanism = SCRAM-SHA-512
	sasl.oauthbearer.clock.skew.seconds = 30
	sasl.oauthbearer.expected.audience = null
	sasl.oauthbearer.expected.issuer = null
	sasl.oauthbearer.header.urlencode = false
	sasl.oauthbearer.jwks.endpoint.refresh.ms = 3600000
	sasl.oauthbearer.jwks.endpoint.retry.backoff.max.ms = 10000
	sasl.oauthbearer.jwks.endpoint.retry.backoff.ms = 100
	sasl.oauthbearer.jwks.endpoint.url = null
	sasl.oauthbearer.scope.claim.name = scope
	sasl.oauthbearer.sub.claim.name = sub
	sasl.oauthbearer.token.endpoint.url = null
	security.protocol = SASL_PLAINTEXT
	security.providers = null
	send.buffer.bytes = 131072
	socket.connection.setup.timeout.max.ms = 30000
	socket.connection.setup.timeout.ms = 10000
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.3]
	ssl.endpoint.identification.algorithm = https
	ssl.engine.factory.class = null
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.certificate.chain = null
	ssl.keystore.key = null
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLSv1.3
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.certificates = null
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS
	transaction.timeout.ms = 60000
	transactional.id = null
	value.serializer = class org.apache.kafka.common.serialization.ByteArraySerializer
2025-11-07 07:49:05 INFO  [vert.x-eventloop-thread-0] KafkaMetricsCollector:270 - initializing Kafka metrics collector
2025-11-07 07:49:05 INFO  [vert.x-eventloop-thread-0] KafkaProducer:610 - [Producer clientId=producer-1] Instantiated an idempotent producer.
2025-11-07 07:49:05 INFO  [vert.x-eventloop-thread-0] AbstractConfig:380 - These configurations '[config.providers, config.providers.strimzifile.class, config.providers.strimzifile.param.allowed.paths, config.providers.strimzienv.param.allowlist.pattern, config.providers.strimzidir.class, config.providers.strimzidir.param.allowed.paths, config.providers.strimzienv.class]' were supplied but are not used yet.
2025-11-07 07:49:05 INFO  [vert.x-eventloop-thread-0] AppInfoParser:125 - Kafka version: 4.0.0
2025-11-07 07:49:05 INFO  [vert.x-eventloop-thread-0] AppInfoParser:126 - Kafka commitId: 985bc99521dd22bb
2025-11-07 07:49:05 INFO  [vert.x-eventloop-thread-0] AppInfoParser:127 - Kafka startTimeMs: 1762501745502
2025-11-07 07:49:05 INFO  [kafka-producer-network-thread | producer-1] Metadata:365 - [Producer clientId=producer-1] Cluster ID: JqlWQWEDSdC0pEyw784xoQ
2025-11-07 07:49:05 INFO  [kafka-producer-network-thread | producer-1] TransactionManager:566 - [Producer clientId=producer-1] ProducerId set to 16268 with epoch 0
2025-11-07 07:49:05 INFO  [Thread-4] send:58 - [2095516019] SEND Response: statusCode = 200, message = OK
2025-11-07 07:49:06 INFO  [vert.x-eventloop-thread-0] KafkaProducer:1367 - [Producer clientId=producer-1] Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
2025-11-07 07:49:06 INFO  [vert.x-eventloop-thread-0] Metrics:684 - Metrics scheduler closed
2025-11-07 07:49:06 INFO  [vert.x-eventloop-thread-0] Metrics:688 - Closing reporter org.apache.kafka.common.metrics.JmxReporter
2025-11-07 07:49:06 INFO  [vert.x-eventloop-thread-0] Metrics:688 - Closing reporter org.apache.kafka.common.telemetry.internals.ClientTelemetryReporter
2025-11-07 07:49:06 INFO  [vert.x-eventloop-thread-0] Metrics:694 - Metrics reporters closed
2025-11-07 07:49:06 INFO  [vert.x-eventloop-thread-0] AppInfoParser:89 - App info kafka.producer for producer-1 unregistered
```

**Comment by ppatierno** [comment]
@joschi we should avoid to comment on a closed issue but I just ran your command on both 0.32.0 and latest 0.33.1 and it works as expected. If you remove the `f` option from the cURL command I can also see the JSON error returned by the bridge with a HTTP 400 as error code. 

```shell
curl -iS -X POST -d '{"records":[{"key":"key-1", "value": "value-1"},{"key":"key-2", "value":"value-2"}]}' localhost:8080/topics/bridge-test
HTTP/1.1 400 Bad Request
content-type: application/vnd.kafka.v2+json
content-length: 122

{"error_code":400,"message":"[Bad Request] Cannot find body processor for content type application/x-www-form-urlencoded"}
```

I see it in the bridge log as well:

```shell
2025-11-07 09:24:31 ERROR [vert.x-eventloop-thread-0] HttpBridge:636 - [344043034] Request: from 0:0:0:0:0:0:0:1:46334, method = POST, path = /topics/bridge-test
2025-11-07 09:24:31 ERROR [vert.x-eventloop-thread-0] HttpBridge:671 - [344043034] Response: statusCode = 400, message = [Bad Request] Cannot find body processor for content type application/x-www-form-urlencoded
```
