### ISSUE TITLE
Unable to GET/POST from Kakfa Bridge

### ISSUE THREAD

**Issue by alpacino12** [strimzi/strimzi-kafka-bridge#612]
I have a running instance of strimzi kafka cluster on Azure kubernetes Service . The cluster is enabled with SCRAM-SHA-512 authentication and tls is  enabled . 

I have deployed a kafka bridge using kafka-bridge template and the deployment for the bridge succeeded . When i try to access the bridge from curl/post http://20.80.69.53:8080/ it gives 200 connection ok 
`{
    "bridge_version": "0.19.0"
}
`
However , when i try http://20.80.69.53:8080/topics , it times out and does not fetch the topic metadata

I'm quite sure its related to the tls configuration set to true and scram-sha-512 mode of authentcation used , the problem is even when i try to pass the user/password and certificate to the bridge , it simply does'nt connect . How can i connect to the bridge with credentials ? Is it even allowed ? I tried with plain mode and no tls and i was able to get topic metadata as well from kafka bridge , that means it works with tls disabled . How can i make it work with tls enabled ? its not working when i pass the credentials and certificate , below is my deployment listener section

`kafka:
    config:
      inter.broker.protocol.version: 2.7
      log.message.format.version: 2.7
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 3
      transaction.state.log.replication.factor: 3
    listeners:
    - authentication:
        type: scram-sha-512
      name: tls
      port: 9093
      tls: false
      type: internal
    - authentication:
        type: scram-sha-512
      name: extnl
      port: 9094
      tls: true
      type: loadbalancer`

I have an external kafka bootstrap server which exposes external load balancer to access the cluster . All pods are running , below are the services

`tushar@Azure:~$ kubectl get svc -n strimzi-operator-aks-cluster
NAME                                        TYPE           CLUSTER-IP     EXTERNAL-IP      PORT(S)                      AGE
bridge-dep-tls-bridge-service               ClusterIP      10.0.159.125   <none>           8080/TCP                     3d18h
bridge-no-tls-bridge-service                ClusterIP      10.0.29.236    <none>           8080/TCP                     3d17h
bridge-rest-service                         LoadBalancer   10.0.56.23     20.80.69.53      8080:32724/TCP               11d
kafka-bridge-bridge-service                 ClusterIP      10.0.179.116   <none>           8080/TCP                     3d18h
kafka-connect-cluster-connect-api           ClusterIP      10.0.236.123   <none>           8083/TCP                     214d
kafka-gsmdp-cluster-kafka-bootstrap         ClusterIP      10.0.139.101   <none>           9091/TCP,9093/TCP            236d
kafka-gsmdp-cluster-kafka-brokers           ClusterIP      None           <none>           9090/TCP,9091/TCP,9093/TCP   236d
kafka-gsmdp-cluster-kafka-extnl-0           LoadBalancer   10.0.247.233   52.182.216.62    9094:32221/TCP               236d
kafka-gsmdp-cluster-kafka-extnl-1           LoadBalancer   10.0.107.4     52.182.216.76    9094:31083/TCP               236d
kafka-gsmdp-cluster-kafka-extnl-2           LoadBalancer   10.0.121.143   52.182.216.167   9094:30207/TCP               236d
kafka-gsmdp-cluster-kafka-extnl-bootstrap   LoadBalancer   10.0.197.248   52.182.216.185   9094:31607/TCP               236d
kafka-gsmdp-cluster-zookeeper-client        ClusterIP      10.0.47.81     <none>           2181/TCP                     236d
kafka-gsmdp-cluster-zookeeper-nodes         ClusterIP      None           <none>           2181/TCP,2888/TCP,3888/TCP   236d
my-connect-cluster-connect-api              ClusterIP      10.0.213.224   <none>           8083/TCP                     235d
new-bridge-service                          LoadBalancer   10.0.150.104   20.84.200.137    8080:32493/TCP               3d18h
notls-bridge-service                        LoadBalancer   10.0.145.253   20.98.184.27     8080:31112/TCP               3d17h
strimzi-aks-bridge-bridge-service           ClusterIP      10.0.253.89    <none>           8080/TCP                     11d`

Thanks
Best Regards

**Comment by scholzj** [comment]
What is _kafka-bridge template_? I guess you will need to share some logs from the bridge and from Kafka, you will also ned to share your Bridge configuration.

**Comment by alpacino12** [comment]
I tried creating bridges with tls config and without . Yaml file used for creating the bridge with no tls

```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaBridge
metadata:
  name: bridge-no-tls
spec:
  replicas: 1
  bootstrapServers: kafka-gsmdp-cluster-kafka-extnl-bootstrap:9094
  http:
    port: 8080

```
Logs from the kafka bridge pod
```
timed out at 1649430561064 after 1 attempt(s)
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment.
2022-04-08 15:09:51 INFO  AdminMetadataManager:235 - [AdminClient clientId=adminclient-1] Metadata update failed
org.apache.kafka.common.errors.TimeoutException: Call(callName=fetchMetadata, deadlineMs=1649430591064, tries=1, nextAllowedTryMs=1649430591165) timed out at 1649430591065 after 1 attempt(s)
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting to send the call.
2022-04-08 15:10:21 INFO  AdminMetadataManager:235 - [AdminClient clientId=adminclient-1] Metadata update failed
org.apache.kafka.common.errors.TimeoutException: Call(callName=fetchMetadata, deadlineMs=1649430621065, tries=1, nextAllowedTryMs=1649430621166) timed out at 1649430621066 after 1 attempt(s)
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment.
2022-04-08 15:10:51 INFO  AdminMetadataManager:235 - [AdminClient clientId=adminclient-1] Metadata update failed
org.apache.kafka.common.errors.TimeoutException: Call(callName=fetchMetadata, deadlineMs=1649430651066, tries=1, nextAllowedTryMs=1649430651167) timed out at 1649430651067 after 1 attempt(s)
```

Bridge with tls settings

```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaBridge
metadata:
  name: bridge-dep-tls
spec:
  replicas: 1
  bootstrapServers: kafka-gsmdp-cluster-kafka-extnl-bootstrap:9094
  tls:
    trustedCertificates:
      - secretName: kafka-gsmdp-cluster-cluster-ca-cert
        certificate: ca.crt
  authentication:
    type: scram-sha-512
    username: my-user
    passwordSecret:
      secretName: my-user
      password: password
  http:
    port: 8080
```
Bridge pod logs

```
2022-04-11 09:39:11 ERROR NetworkClient:746 - [AdminClient clientId=adminclient-1] Connection to node -1 (kafka-gsmdp-cluster-kafka-extnl-bootstrap/10.0.197.248:9094) failed authentication due to: SSL handshake failed
2022-04-11 09:39:11 WARN  AdminMetadataManager:232 - [AdminClient clientId=adminclient-1] Metadata update failed due to authentication error
org.apache.kafka.common.errors.SslAuthenticationException: SSL handshake failed
Caused by: javax.net.ssl.SSLHandshakeException: No subject alternative DNS name matching kafka-gsmdp-cluster-kafka-extnl-bootstrap found.
        at sun.security.ssl.Alert.createSSLException(Alert.java:131) ~[?:?]
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:326) ~[?:?]
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:269) ~[?:?]
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:264) ~[?:?]
        at sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1339) ~[?:?]
        at sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1214) ~[?:?]
        at sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1157) ~[?:?]
        at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392) ~[?:?]
        at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444) ~[?:?]
        at sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1074) ~[?:?]
        at sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1061) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1008) ~[?:?]
        at org.apache.kafka.common.network.SslTransportLayer.runDelegatedTasks(SslTransportLayer.java:430) ~[kafka-clients-2.6.0.jar:?]
        at org.apache.kafka.common.network.SslTransportLayer.handshakeUnwrap(SslTransportLayer.java:514) ~[kafka-clients-2.6.0.jar:?]
        at org.apache.kafka.common.network.SslTransportLayer.doHandshake(SslTransportLayer.java:368) ~[kafka-clients-2.6.0.jar:?]
```

**Comment by scholzj** [comment]
Well, in the first case, you clearly didn't configured the security. So I think that is quite clear. In the second, you did that. But you seem to be using a load balancer listener. If you really want to do it, use the Load Balancer IP address or DNs name to configure the connection. You should be able to find it in the status of the Kafka custom resource. But normally, if they run in the same Kubernetes cluster, you would use an internal listener such as the one oyu have on port 9093 and not connect through the load balancer listener since that can cause additional costs and have some performance impact as well.

**Comment by alpacino12** [comment]
You're the man ! I certainly owe you a beer sometime if I'm in Prague .

Tried passing the  external loadbalancer ip in the bridge configuration , works perfectly ! 

```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaBridge
metadata:
  name: bridge-dep-tls
spec:
  replicas: 1
  bootstrapServers: 52.182.216.185:9094
  tls:
    trustedCertificates:
      - secretName: kafka-gsmdp-cluster-cluster-ca-cert
        certificate: ca.crt
  authentication:
    type: scram-sha-512
    username: my-user
    passwordSecret:
      secretName: my-user
      password: password
  http:
    port: 8080
```

Connection working from outside the cluster as well , which was my end goal

![image](https://user-images.githubusercontent.com/30342066/162757282-7fb2cb1c-64f2-4179-b990-bdb08a323cf0.png)

i was stuck on this issue for the last 2-3 days , glad it got resolved now . One thing i want to check is, if is possible to  configure username/password for the bridge or should it behind a reverse proxy/gateway

Thanks  a ton ! Cheers !

**Comment by alpacino12** [comment]
Closing 

BEST REGARDS
