### ISSUE TITLE
Enabling metrics fails bridge startup with `NoClassDefFoundError` exception

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-bridge#688]
When running the bridge, on the main branch, by enabling the metrics (via `KAFKA_BRIDGE_METRICS_ENABLED=true`), it fails with the following exception:

```shell
2022-11-14 08:25:51 INFO  Application:65 - Strimzi Kafka Bridge 0.23.0-SNAPSHOT is starting                                                                                                                                                
 2022-11-14 08:25:51 INFO  Application:70 - Metrics enabled and exposed on the /metrics endpoint                                                                                                                                            
 Exception in thread "main" java.lang.NoClassDefFoundError: io/prometheus/client/exemplars/HistogramExemplarSampler                                                                                                                         
     at io.vertx.micrometer.backends.PrometheusBackendRegistry.<init>(PrometheusBackendRegistry.java:45)                                                                                                                                    
     at io.vertx.micrometer.backends.BackendRegistries.lambda$setupBackend$0(BackendRegistries.java:71)                                                                                                                                     
     at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)                                                                                                                                       
     at io.vertx.micrometer.backends.BackendRegistries.setupBackend(BackendRegistries.java:58)                                                                                                                                              
     at io.vertx.micrometer.impl.VertxMetricsFactoryImpl.metrics(VertxMetricsFactoryImpl.java:54)                                                                                                                                           
     at io.vertx.core.spi.VertxMetricsFactory.init(VertxMetricsFactory.java:50)                                                                                                                                                             
     at io.vertx.core.impl.VertxBuilder.initProviders(VertxBuilder.java:280)                                                                                                                                                                
     at io.vertx.core.impl.VertxBuilder.init(VertxBuilder.java:271)                                                                                                                                                                         
     at io.vertx.core.Vertx.vertx(Vertx.java:86)                                                                                                                                                                                            
     at io.strimzi.kafka.bridge.Application.main(Application.java:75)                                                                                                                                                                       
 Caused by: java.lang.ClassNotFoundException: io.prometheus.client.exemplars.HistogramExemplarSampler                                                                                                                                       
     at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)                                                                                                                                             
     at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)                                                                                                                                          
     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)                                                                                                                                                                     
     ... 10 more          
```

Of course, it happens by running the bridge both locally and Kubernetes (by using "latest" image).
It DOESN'T happen when using the latest 0.22.3 release, so some of the new commits (dependencies update?) have broken metrics somehow.

**Comment by ppatierno** [comment]
So it seems that the problem was caused by bumping the micrometer dependency to `1.9.5` with #680 
Taking a look at the micrometer project, in the latest version it has a direct dependency to the `io.prometheus:simpleclient` but using a version greater than 0.15.0. The bridge has a direct dependency instead still at 0.7.0.
Bumping `io.prometheus:simpleclient` to latest version helps but it also need a bump of the `io.prometheus.jmx:collector` dependency as well.
Btw this issue shows the missing of a proper test on metrics endpoint, which should be addressed.
